INSERT INTO CUSTOMER VALUES(1,'Sumit Ghosh','Garfa','Kolkata','West Bengal','700085')
INSERT INTO CUSTOMER VALUES(2,'Gourab Guha','Garia','Kolkata','West Bengal','700145')
INSERT INTO CUSTOMER VALUES(3,'Debina Guha','Kestopur','Kolkata','West Bengal','700185')
INSERT INTO CUSTOMER VALUES(4,'Debabrata Poddar','Birati','Kolkata','West Bengal','700285')
INSERT INTO CUSTOMER VALUES(5,'Amit Dharmale','Thane','Mumbai','Maharastra','400140')		

INSERT INTO BOOK VALUES(1,'To Kill a Mockingbird','Harper Lee','blah blah..Some extra information about this book',2)
INSERT INTO BOOK VALUES(2,'Harry Potter and the Sorcerers Stone (Harry Potter, #1)','J.K. Rowling','blah blah..Some extra information about this book',3)
INSERT INTO BOOK VALUES(3,'1984','George Orwell','blah blah..Some extra information about this book',4)
INSERT INTO BOOK VALUES(4,'Pride and Prejudice','Jane Austen','blah blah..Some extra information about this book',1)
INSERT INTO BOOK VALUES(5,'The Diary of a Young Girl','Anne Frank','blah blah..Some extra information about this book',5)
INSERT INTO BOOK VALUES(6,'Animal Farm','George Orwell','blah blah..Some extra information about this book',5)
INSERT INTO BOOK VALUES(7,'The Hobbit','J.R.R. Tolkien','blah blah..Some extra information about this book',1)
INSERT INTO BOOK VALUES(8,'The Little Prince','Antoine de Saint-Exupery','blah blah..Some extra information about this book',2)
INSERT INTO BOOK VALUES(9,'The Great Gatsby','F. Scott Fitzgerald','blah blah..Some extra information about this book',3)
INSERT INTO BOOK VALUES(10,'The Catcher in the Rye','J.D. Salinger','blah blah..Some extra information about this book',4)