INSERT INTO CUSTOMER VALUES(1,'James  Butt','6649 N Blue Gum St','New Orleans','LA','70116','504-621-8927','jbutt@gmail.com')
INSERT INTO CUSTOMER VALUES(2,'Josephine  Darakjy','4 B Blue Ridge Blvd','Brighton','MI','48116','810-292-9388','josephine_darakjy@darakjy.org')
INSERT INTO CUSTOMER VALUES(3,'Art  Venere','8 W Cerritos Ave #54','Bridgeport','NJ','8014','856-636-8749','art@venere.org')
INSERT INTO CUSTOMER VALUES(4,'Lenna  Paprocki','639 Main St','Anchorage','AK','99501','907-385-4412','lpaprocki@hotmail.com')
INSERT INTO CUSTOMER VALUES(5,'Donette  Foller','34 Center St','Hamilton','OH','45011','513-570-1893','donette.foller@cox.net')
INSERT INTO CUSTOMER VALUES(6,'Simona  Morasca','3 Mcauley Dr','Ashland','OH','44805','419-503-2484','simona@morasca.com')
INSERT INTO CUSTOMER VALUES(7,'Mitsue  Tollner','7 Eads St','Chicago','IL','60632','773-573-6914','mitsue_tollner@yahoo.com')

INSERT INTO BOOK VALUES(1,'To Kill a Mockingbird','Harper Lee','blah blah..Some extra information about this book',2)
INSERT INTO BOOK VALUES(2,'Harry Potter and the Sorcerers Stone (Harry Potter, #1)','J.K. Rowling','blah blah..Some extra information about this book',3)
INSERT INTO BOOK VALUES(3,'1984','George Orwell','blah blah..Some extra information about this book',4)
INSERT INTO BOOK VALUES(4,'Pride and Prejudice','Jane Austen','blah blah..Some extra information about this book',1)
INSERT INTO BOOK VALUES(5,'The Diary of a Young Girl','Anne Frank','blah blah..Some extra information about this book',5)
INSERT INTO BOOK VALUES(6,'Animal Farm','George Orwell','blah blah..Some extra information about this book',5)
INSERT INTO BOOK VALUES(7,'The Hobbit','J.R.R. Tolkien','blah blah..Some extra information about this book',1)
INSERT INTO BOOK VALUES(8,'The Little Prince','Antoine de Saint-Exupery','blah blah..Some extra information about this book',2)
INSERT INTO BOOK VALUES(9,'The Great Gatsby','F. Scott Fitzgerald','blah blah..Some extra information about this book',3)
INSERT INTO BOOK VALUES(10,'The Catcher in the Rye','J.D. Salinger','blah blah..Some extra information about this book',4)